#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+  Listens on port 80.
#+  Returns a page containing "Hello World" when queried
#+   at the root with a curl GET request.
#+  Configures /redirect_me as a "301 Moved Permanently".
#+  Includes a custom 404 page containing "Ceci n'est pas une page".
#+  Contains a custom HTTP header named X-Served-By.
#+  The value of the HTTP header is the hostname of the running server.

sudo apt-get -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html/
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error-page.html
SERVERCONFIG=\
"server {
        listen 80 default_server;
        add_header X-Served-By $HOSTNAME;
        listen [::]:80 default_server;
        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
        }

        error_page 404 /error-page.html;
        location = /error-page.html {
                root /var/www/html;
                internal;
        }

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"
echo "$SERVERCONFIG" | sudo tee /etc/nginx/sites-enabled/default 
sudo service nginx restart