#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
#+  Configure HAproxy so that it send traffic to web-01 and web-02
#+  Distribute requests using a roundrobin algorithm
#+   Make sure that HAproxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y install haproxy
HAPROXYCONFIG="
frontend haproxy-main
        bind *:80
        mode http
        default_backend task-servers

backend task-servers
        balance roundrobin
        server 10718-web-01 52.86.58.93:80 check
        server 10718-web-02 52.3.250.62:80 check
"

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo echo "$HAPROXYCONFIG" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
